import type { Metadata } from "next";

import { IBM_Plex_Sans } from "next/font/google";

import Header from "@/components/header";
import Providers from "@/components/providers";
import { cn } from "@/lib/utils";

import AppleTouchIcon from "../../public/apple-touch-icon.png";
import Favicon16 from "../../public/favicon-16x16.png";
import Favicon32 from "../../public/favicon-32x32.png";
import "./globals.css";

const ibmPlexSands = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    {
      rel: "apple-touch-icon",
      sizes: "180x180",
      url: AppleTouchIcon.src,
    },
    {
      rel: "icon",
      type: "image/png",
      sizes: "32x32",
      url: Favicon32.src,
    },
    {
      rel: "icon",
      type: "image/png",
      sizes: "16x16",
      url: Favicon16.src,
    },
    {
      rel: "manifest",
      url: "/site.webmanifest",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          ibmPlexSands.variable
        )}
      >
        <Providers>
          <Header />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
